import path from "node:path";
import { app, BrowserWindow, dialog, ipcMain, shell, globalShortcut, session } from "electron";
import { autoUpdater } from "electron-updater";
import type { AiosCommand } from "./types";
import { findClaude, validateClaude } from "./claude-finder";
import { initLogger, log } from "./logger";
import { PythonHost } from "./python-host";
import { AutoTaskScheduler } from "./scheduler";
import { ensureRuntimeWorkspace, getSourceStarterKit } from "./workspace";

let mainWindow: BrowserWindow | null = null;
let host: PythonHost | null = null;
let scheduler: AutoTaskScheduler | null = null;

app.setName("aios-desktop");
app.setAppUserModelId("com.aios.desktop");
if (!app.isPackaged) {
  app.disableHardwareAcceleration();
  app.commandLine.appendSwitch("disable-gpu");
  app.commandLine.appendSwitch("disable-gpu-compositing");
  app.commandLine.appendSwitch("in-process-gpu");
  app.commandLine.appendSwitch("disable-features", "VizDisplayCompositor");
  app.setPath("userData", path.join(process.cwd(), ".aios-dev-user-data"));
}

const mainHandledCommands = new Set<AiosCommand>([
  "find_claude",
  "set_claude_path",
  "test_claude_connection",
  "reveal_in_file_manager",
  "run_auto_task_now"
]);

function createWindow(): void {
  // Resolve the icon if it exists (generated by `node assets/generate-icons.js`).
  const iconPath = path.join(__dirname, "..", "..", "assets", "icon.png");
  const fs = require("fs");
  const icon = fs.existsSync(iconPath) ? iconPath : undefined;

  // On Mac use "hiddenInset" so the system traffic-light buttons stay visible
  // (inset into our drag region). On Windows we keep the chromeless look and
  // render our own minimize/maximize/close controls in the renderer.
  const isMac = process.platform === "darwin";
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1040,
    minHeight: 720,
    title: "AIOS Desktop",
    frame: !isMac ? false : undefined,
    backgroundColor: "#fafaf7",
    titleBarStyle: isMac ? "hiddenInset" : "hidden",
    trafficLightPosition: isMac ? { x: 18, y: 18 } : undefined,
    icon,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  });

  const devUrl = process.env.VITE_DEV_SERVER_URL;
  if (devUrl) {
    mainWindow.loadURL(devUrl);
  } else {
    mainWindow.loadFile(path.join(__dirname, "..", "renderer", "index.html"));
  }

  // Route every link click / window.open / target=_blank that the renderer
  // emits into the user's default system browser. Without this, Electron
  // either replaces the app window with the destination page or pops up an
  // ugly bare BrowserWindow. The OAuth flow has its own explicit IPC
  // (aios:open-external + aios:open-oauth-window) and isn't affected.
  const internalOrigins = new Set<string>();
  if (devUrl) internalOrigins.add(new URL(devUrl).origin);

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//i.test(url) || /^mailto:/i.test(url)) {
      void shell.openExternal(url);
    }
    return { action: "deny" };
  });

  mainWindow.webContents.on("will-navigate", (event, url) => {
    try {
      const target = new URL(url);
      // Allow same-origin SPA navigation (Vite HMR, route changes inside the
      // renderer); push everything else to the system browser.
      if (target.protocol === "file:" || internalOrigins.has(target.origin)) return;
      event.preventDefault();
      if (target.protocol === "http:" || target.protocol === "https:" || target.protocol === "mailto:") {
        void shell.openExternal(url);
      }
    } catch {
      event.preventDefault();
    }
  });

  mainWindow.on("maximize", () => {
    if (!mainWindow?.isDestroyed()) mainWindow?.webContents.send("window:maximized-changed", true);
  });
  mainWindow.on("unmaximize", () => {
    if (!mainWindow?.isDestroyed()) mainWindow?.webContents.send("window:maximized-changed", false);
  });
  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

function registerIpcHandlers(): void {
  // Window control IPC handlers
  ipcMain.on("window:minimize", () => mainWindow?.minimize());
  ipcMain.on("window:maximize", () => {
    if (mainWindow?.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow?.maximize();
    }
  });
  ipcMain.on("window:close", () => mainWindow?.close());

  // Open URL in the OS default browser (used for help/docs links).
  if (ipcMain.handle) {
    ipcMain.removeHandler("aios:open-external");
    ipcMain.handle("aios:open-external", async (_event, url: string) => {
      if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
      if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };
      try {
        await shell.openExternal(url);
        return { ok: true };
      } catch (err) {
        return { ok: false, error: err instanceof Error ? err.message : String(err) };
      }
    });

    ipcMain.removeHandler("aios:open-oauth-window");
    ipcMain.handle("aios:open-oauth-window", async (_event, url: string) => {
      if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
      if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };

      const partition = `oauth-${Date.now()}`;
      const oauthSession = session.fromPartition(partition);
      try {
        await oauthSession.clearStorageData();
      } catch { /* fresh partition is already empty */ }

      // Force Google's OAuth flow to show the account picker every time
      oauthSession.webRequest.onBeforeRequest(
        { urls: ["https://accounts.google.com/o/oauth2/*"] },
        (details, callback) => {
          try {
            const url = new URL(details.url);
            if (
              (url.pathname.startsWith("/o/oauth2/v2/auth") || url.pathname.startsWith("/o/oauth2/auth")) &&
              !url.searchParams.has("prompt")
            ) {
              url.searchParams.set("prompt", "select_account");
              callback({ redirectURL: url.toString() });
              return;
            }
          } catch { /* fall through */ }
          callback({});
        }
      );

      return await new Promise<{ ok: boolean; completed?: boolean; error?: string }>((resolve) => {
        const win = new BrowserWindow({
          width: 540,
          height: 720,
          title: "Connect account",
          parent: mainWindow ?? undefined,
          modal: false,
          autoHideMenuBar: true,
          backgroundColor: "#fafaf7",
          webPreferences: {
            session: oauthSession,
            contextIsolation: true,
            nodeIntegration: false,
            sandbox: true,
            enableWebSQL: false,
          },
        });

        let resolved = false;
        const safeResolve = (payload: { ok: boolean; completed?: boolean; error?: string }) => {
          if (resolved) return;
          resolved = true;
          resolve(payload);
        };

        win.on("closed", () => {
          safeResolve({ ok: true, completed: false });
        });

        win.loadURL(url).catch((err: unknown) => {
          safeResolve({
            ok: false,
            error: err instanceof Error ? err.message : String(err),
          });
          try { win.close(); } catch { /* noop */ }
        });
      });
    });
  }

  // Global shortcut for preferences
  globalShortcut.register("Command+,", () => {
    if (!mainWindow?.isDestroyed()) mainWindow?.webContents.send("shortcut:preferences");
  });
}

async function getSavedClaudePath(): Promise<string | null> {
  const response = await host?.invoke<{ value: string | null }>("get_setting", { key: "claude_path" });
  return response?.ok ? response.data?.value ?? null : null;
}

async function handleMainCommand(cmd: AiosCommand, args: Record<string, unknown>) {
  if (!host) throw new Error("Python host not initialized");

  if (cmd === "find_claude") {
    const savedPath = await getSavedClaudePath();
    const result = await findClaude(savedPath);
    if (result.found && result.path) {
      await host.invoke("set_setting", { key: "claude_path", value: result.path });
      await host.invoke("set_setting", { key: "claude_version", value: result.version ?? "" });
    }
    return result;
  }

  if (cmd === "set_claude_path") {
    let selectedPath = String(args.path ?? "");
    if (!selectedPath && args.browse === true) {
      const result = await dialog.showOpenDialog({
        title: "Select Claude Code executable",
        properties: ["openFile"]
      });
      selectedPath = result.filePaths[0] ?? "";
    }
    const validation = await validateClaude(selectedPath);
    if (!validation.ok) {
      return { stored: false, ...validation };
    }
    await host.invoke("set_setting", { key: "claude_path", value: selectedPath });
    await host.invoke("set_setting", { key: "claude_version", value: validation.version ?? "" });
    return { stored: true, path: selectedPath, version: validation.version };
  }

  if (cmd === "test_claude_connection") {
    const pathArg = typeof args.path === "string" ? args.path : await getSavedClaudePath();
    if (!pathArg) return { ok: false, version: null, error: "Claude path is not configured." };
    const validation = await validateClaude(pathArg);
    return { ok: validation.ok, path: pathArg, version: validation.version, error: validation.error };
  }

  if (cmd === "reveal_in_file_manager") {
    const relativePath = String(args.path ?? "");
    if (!relativePath) throw new Error("Path is required.");
    const workspaceRoot = ensureRuntimeWorkspace();
    const absolutePath = path.resolve(workspaceRoot, relativePath);
    if (absolutePath !== workspaceRoot && !absolutePath.startsWith(`${workspaceRoot}${path.sep}`)) {
      throw new Error("Path escapes runtime workspace.");
    }
    shell.showItemInFolder(absolutePath);
    return { ok: true, path: relativePath };
  }

  if (cmd === "run_auto_task_now") {
    const taskId = Number(args.taskId);
    if (!Number.isFinite(taskId)) throw new Error("taskId is required.");
    if (!scheduler) throw new Error("Scheduler is not running.");
    scheduler.runOnce(taskId).catch((err) => log("scheduler", "manual run failed", { error: err instanceof Error ? err.message : String(err) }));
    return { ok: true, taskId };
  }

  throw new Error(`Unhandled main command: ${cmd}`);
}

app.whenReady().then(() => {
  session.defaultSession.setPermissionRequestHandler((_webContents, permission, callback) => {
    callback(permission === "media");
  });
  session.defaultSession.setPermissionCheckHandler((_webContents, permission) => {
    return permission === "media";
  });

  const workspaceRoot = ensureRuntimeWorkspace();
  const starterKitRoot = getSourceStarterKit();
  initLogger(workspaceRoot);
  host = new PythonHost(workspaceRoot, starterKitRoot);
  host.onEvent((event) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("aios:host-event", event);
    }
  });
  let hostStarted = false;
  try {
    host.start();
    hostStarted = true;
  } catch (error) {
    log("python", "host failed to start", { error: error instanceof Error ? error.message : String(error) });
  }
  scheduler = new AutoTaskScheduler(host);
  if (hostStarted) scheduler.start();

  ipcMain.handle("aios:invoke", async (_event, cmd: AiosCommand, args: Record<string, unknown> = {}) => {
    try {
      if (mainHandledCommands.has(cmd)) {
        return { ok: true, data: await handleMainCommand(cmd, args) };
      }

      const response = await host?.invoke(cmd, args);
      if (!response) return { ok: false, error: { code: "HOST_MISSING", message: "Python host is not running." } };
      return response.ok ? { ok: true, data: response.data } : { ok: false, error: response.error };
    } catch (error) {
      log("main.ipc", "command failed", { cmd, error: error instanceof Error ? error.message : String(error) });
      return {
        ok: false,
        error: {
          code: "MAIN_ERROR",
          message: error instanceof Error ? error.message : String(error)
        }
      };
    }
  });

  registerIpcHandlers();
  createWindow();

  const broadcast = (state: string, payload?: Record<string, unknown>) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("aios:update-state", { state, ...payload });
    }
  };

  // electron-updater's in-place auto-update requires the .app bundle to be
  // code-signed on macOS (Squirrel.Mac validates the new bundle's signature
  // against the running app's signature before swapping). Our Mac builds
  // are unsigned today, so any in-place update attempt throws:
  //   "code failed to satisfy specified code requirement(s)"
  // Until we get an Apple Developer ID cert + notarization, Mac users get a
  // "manual download" experience: we hit GitHub's API to see what's the
  // latest release, and offer a button that opens the release page in their
  // default browser.
  //
  // Windows is unaffected — NSIS doesn't have the same signing constraint,
  // and our auto-update has been working there.
  const isMac = process.platform === "darwin";

  if (app.isPackaged && !isMac) {
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    autoUpdater.on("checking-for-update", () => broadcast("checking"));
    autoUpdater.on("update-available", (info) => {
      log("updater", "update-available", { version: info.version });
      broadcast("available", { version: info.version });
    });
    autoUpdater.on("update-not-available", (info) => broadcast("up-to-date", { version: info.version }));
    autoUpdater.on("download-progress", (p) => broadcast("downloading", { percent: Math.round(p.percent) }));
    autoUpdater.on("update-downloaded", (info) => {
      log("updater", "update-downloaded", { version: info.version });
      broadcast("ready", { version: info.version });
    });
    autoUpdater.on("error", (err) => {
      log("updater", "error", { error: err.message });
      broadcast("error", { message: err.message });
    });

    autoUpdater.checkForUpdatesAndNotify().catch((err) => log("updater", "check-failed", { error: err?.message }));
  }

  // Compare semver-like versions: returns true if `latest` is strictly newer
  // than `current`. Stripping a leading "v" lets us compare GH tag names
  // ("v0.1.9") against package.json versions ("0.1.9") interchangeably.
  function isNewerVersion(latest: string, current: string): boolean {
    const parse = (v: string) => v.replace(/^v/i, "").split(/[.-]/).map((n) => Number(n) || 0);
    const lp = parse(latest);
    const cp = parse(current);
    for (let i = 0; i < Math.max(lp.length, cp.length); i++) {
      const l = lp[i] ?? 0;
      const c = cp[i] ?? 0;
      if (l > c) return true;
      if (l < c) return false;
    }
    return false;
  }

  // Mac-only manual update check: query GitHub's releases/latest endpoint
  // (no auth required for public repos), compare versions, broadcast a
  // "manual-available" state with the release URL when newer.
  async function checkForUpdatesManual(): Promise<{
    ok: boolean;
    currentVersion: string;
    latestVersion?: string;
    hasUpdate?: boolean;
    manualDownloadUrl?: string;
    reason?: string;
    error?: string;
  }> {
    const currentVersion = app.getVersion();
    try {
      broadcast("checking");
      const res = await fetch(
        "https://api.github.com/repos/satyaprakashmallidi/AIOS_Desktop/releases/latest",
        { headers: { Accept: "application/vnd.github+json", "User-Agent": "AIOS-Desktop" } }
      );
      if (!res.ok) {
        broadcast("error", { message: `GitHub API ${res.status}` });
        return { ok: false, currentVersion, reason: "check-failed", error: `GitHub API ${res.status}` };
      }
      const data = (await res.json()) as { tag_name?: string; html_url?: string };
      const tag = data.tag_name ?? "";
      const latestVersion = tag.replace(/^v/i, "");
      const url = data.html_url ?? `https://github.com/satyaprakashmallidi/AIOS_Desktop/releases/latest`;
      if (isNewerVersion(latestVersion, currentVersion)) {
        broadcast("manual-available", { version: latestVersion, manualDownloadUrl: url });
        return { ok: true, currentVersion, latestVersion, hasUpdate: true, manualDownloadUrl: url };
      }
      broadcast("up-to-date", { version: currentVersion });
      return { ok: true, currentVersion, latestVersion, hasUpdate: false };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      broadcast("error", { message });
      return { ok: false, currentVersion, reason: "check-failed", error: message };
    }
  }

  // IPC: returns the currently-running app's version (from package.json).
  ipcMain.handle("aios:get-version", () => app.getVersion());

  // IPC: manual "Check for updates" trigger from Settings.
  ipcMain.handle("aios:check-for-updates", async () => {
    if (!app.isPackaged) {
      return { ok: false, reason: "not-packaged", currentVersion: app.getVersion() };
    }
    if (isMac) {
      // Mac uses manual download path because electron-updater requires
      // code-signed bundles for ShipIt to swap the app in place.
      return await checkForUpdatesManual();
    }
    try {
      const result = await autoUpdater.checkForUpdates();
      return {
        ok: true,
        currentVersion: app.getVersion(),
        latestVersion: result?.updateInfo?.version ?? app.getVersion(),
        hasUpdate: !!result?.updateInfo && result.updateInfo.version !== app.getVersion()
      };
    } catch (err) {
      return { ok: false, reason: "check-failed", error: err instanceof Error ? err.message : String(err) };
    }
  });

  // IPC: install the downloaded update + restart.
  ipcMain.handle("aios:install-update", async () => {
    if (!app.isPackaged) return { ok: false, reason: "not-packaged" };
    if (isMac) {
      // On Mac there is no downloaded update to install — the renderer
      // should be calling openExternal(manualDownloadUrl) directly when the
      // state is "manual-available". Returning a clear reason in case it
      // doesn't.
      return { ok: false, reason: "manual-only-on-mac" };
    }
    try {
      autoUpdater.quitAndInstall();
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

let isCleaningUp = false;
app.on("before-quit", (event) => {
  if (isCleaningUp) return;
  isCleaningUp = true;
  event.preventDefault();
  scheduler?.stop();
  // host.stop() may be async — fire it, then exit on settle. Give it a 1.5s
  // ceiling so a wedged Python sidecar can't keep the app from quitting.
  const stopHost = Promise.resolve(host?.stop()).catch(() => undefined);
  const watchdog = new Promise<void>((resolve) => setTimeout(resolve, 1500));
  Promise.race([stopHost, watchdog]).finally(() => app.exit(0));
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
