import path from "node:path";
import { app, BrowserWindow, dialog, ipcMain, shell, globalShortcut, session } from "electron";
import { autoUpdater } from "electron-updater";
import type { AiosCommand } from "./types";
import { findClaude, validateClaude } from "./claude-finder";
import { initLogger, log } from "./logger";
import { PythonHost } from "./python-host";
import { AutoTaskScheduler } from "./scheduler";
import { ensureRuntimeWorkspace } from "./workspace";

let mainWindow: BrowserWindow | null = null;
let host: PythonHost | null = null;
let scheduler: AutoTaskScheduler | null = null;

app.setName("aios-desktop");
app.setAppUserModelId("com.aios.desktop");

const mainHandledCommands = new Set<AiosCommand>([
  "find_claude",
  "set_claude_path",
  "test_claude_connection",
  "reveal_in_file_manager",
  "run_auto_task_now"
]);

function createWindow(): void {
  // Resolve the icon if it exists (generated by `node assets/generate-icons.js`).
  const iconPath = path.join(__dirname, "..", "..", "assets", "icon.png");
  const fs = require("fs");
  const icon = fs.existsSync(iconPath) ? iconPath : undefined;

  // On Mac use "hiddenInset" so the system traffic-light buttons stay visible
  // (inset into our drag region). On Windows we keep the chromeless look and
  // render our own minimize/maximize/close controls in the renderer.
  const isMac = process.platform === "darwin";
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1040,
    minHeight: 720,
    title: "AIOS Desktop",
    frame: !isMac ? false : undefined,
    backgroundColor: "#fafaf7",
    titleBarStyle: isMac ? "hiddenInset" : "hidden",
    trafficLightPosition: isMac ? { x: 14, y: 14 } : undefined,
    icon,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  });

  // Window control IPC handlers
  ipcMain.on("window:minimize", () => mainWindow?.minimize());
  ipcMain.on("window:maximize", () => {
    if (mainWindow?.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow?.maximize();
    }
  });
  ipcMain.on("window:close", () => mainWindow?.close());

  // Open URL in the OS default browser (used for help/docs links).
  ipcMain.handle("aios:open-external", async (_event, url: string) => {
    if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
    if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };
    try {
      await shell.openExternal(url);
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  // Embedded OAuth window with an isolated, freshly-cleared session.
  // Used by Connectors so the OAuth flow never inherits whatever Google
  // account is signed into the user's default browser.
  ipcMain.handle("aios:open-oauth-window", async (_event, url: string) => {
    if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
    if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };

    const partition = `oauth-${Date.now()}`;
    const oauthSession = session.fromPartition(partition);
    try {
      await oauthSession.clearStorageData();
    } catch { /* fresh partition is already empty */ }

    // Force Google's OAuth flow to show the account picker every time, even
    // if the system has a cached Google identity. Without this, Chromium's
    // built-in credential / autofill integration can silently auto-authorize
    // the wrong account (we hit this bug with `tradephani@gmail.com` getting
    // picked despite the fresh-cookie partition).
    oauthSession.webRequest.onBeforeRequest(
      { urls: ["https://accounts.google.com/o/oauth2/*"] },
      (details, callback) => {
        try {
          const url = new URL(details.url);
          if (
            (url.pathname.startsWith("/o/oauth2/v2/auth") || url.pathname.startsWith("/o/oauth2/auth")) &&
            !url.searchParams.has("prompt")
          ) {
            url.searchParams.set("prompt", "select_account");
            callback({ redirectURL: url.toString() });
            return;
          }
        } catch { /* fall through */ }
        callback({});
      }
    );

    return await new Promise<{ ok: boolean; completed?: boolean; error?: string }>((resolve) => {
      const win = new BrowserWindow({
        width: 540,
        height: 720,
        title: "Connect account",
        parent: mainWindow ?? undefined,
        modal: false,
        autoHideMenuBar: true,
        backgroundColor: "#fafaf7",
        webPreferences: {
          session: oauthSession,
          contextIsolation: true,
          nodeIntegration: false,
          sandbox: true,
          // No password manager / autofill in this isolated session.
          enableWebSQL: false,
        },
      });

      let resolved = false;
      const safeResolve = (payload: { ok: boolean; completed?: boolean; error?: string }) => {
        if (resolved) return;
        resolved = true;
        resolve(payload);
      };

      // No auto-close. Composio's OAuth flow has several intermediate
      // redirects; matching on URL substrings reliably misfires (we used to
      // close the window mid-OAuth before the user could even sign in).
      // The user closes manually once they see Composio's success page;
      // the relay polling in ConnectorsScreen detects completion on its own.

      win.on("closed", () => {
        safeResolve({ ok: true, completed: false });
      });

      win.loadURL(url).catch((err: unknown) => {
        safeResolve({
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        });
        try { win.close(); } catch { /* noop */ }
      });
    });
  });

  // Global shortcut for preferences
  globalShortcut.register("Command+,", () => {
    mainWindow?.webContents.send("shortcut:preferences");
  });

  const devUrl = process.env.VITE_DEV_SERVER_URL;
  if (devUrl) {
    mainWindow.loadURL(devUrl);
  } else {
    mainWindow.loadFile(path.join(__dirname, "..", "renderer", "index.html"));
  }

  // Route every link click / window.open / target=_blank that the renderer
  // emits into the user's default system browser. Without this, Electron
  // either replaces the app window with the destination page or pops up an
  // ugly bare BrowserWindow. The OAuth flow has its own explicit IPC
  // (aios:open-external + aios:open-oauth-window) and isn't affected.
  const internalOrigins = new Set<string>();
  if (devUrl) internalOrigins.add(new URL(devUrl).origin);

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//i.test(url) || /^mailto:/i.test(url)) {
      void shell.openExternal(url);
    }
    return { action: "deny" };
  });

  mainWindow.webContents.on("will-navigate", (event, url) => {
    try {
      const target = new URL(url);
      // Allow same-origin SPA navigation (Vite HMR, route changes inside the
      // renderer); push everything else to the system browser.
      if (target.protocol === "file:" || internalOrigins.has(target.origin)) return;
      event.preventDefault();
      if (target.protocol === "http:" || target.protocol === "https:" || target.protocol === "mailto:") {
        void shell.openExternal(url);
      }
    } catch {
      event.preventDefault();
    }
  });

  mainWindow.on("maximize", () => mainWindow?.webContents.send("window:maximized-changed", true));
  mainWindow.on("unmaximize", () => mainWindow?.webContents.send("window:maximized-changed", false));
}

async function getSavedClaudePath(): Promise<string | null> {
  const response = await host?.invoke<{ value: string | null }>("get_setting", { key: "claude_path" });
  return response?.ok ? response.data?.value ?? null : null;
}

async function handleMainCommand(cmd: AiosCommand, args: Record<string, unknown>) {
  if (!host) throw new Error("Python host not initialized");

  if (cmd === "find_claude") {
    const savedPath = await getSavedClaudePath();
    const result = await findClaude(savedPath);
    if (result.found && result.path) {
      await host.invoke("set_setting", { key: "claude_path", value: result.path });
      await host.invoke("set_setting", { key: "claude_version", value: result.version ?? "" });
    }
    return result;
  }

  if (cmd === "set_claude_path") {
    let selectedPath = String(args.path ?? "");
    if (!selectedPath && args.browse === true) {
      const result = await dialog.showOpenDialog({
        title: "Select Claude Code executable",
        properties: ["openFile"]
      });
      selectedPath = result.filePaths[0] ?? "";
    }
    const validation = await validateClaude(selectedPath);
    if (!validation.ok) {
      return { stored: false, ...validation };
    }
    await host.invoke("set_setting", { key: "claude_path", value: selectedPath });
    await host.invoke("set_setting", { key: "claude_version", value: validation.version ?? "" });
    return { stored: true, path: selectedPath, version: validation.version };
  }

  if (cmd === "test_claude_connection") {
    const pathArg = typeof args.path === "string" ? args.path : await getSavedClaudePath();
    if (!pathArg) return { ok: false, version: null, error: "Claude path is not configured." };
    const validation = await validateClaude(pathArg);
    return { ok: validation.ok, path: pathArg, version: validation.version, error: validation.error };
  }

  if (cmd === "reveal_in_file_manager") {
    const relativePath = String(args.path ?? "");
    if (!relativePath) throw new Error("Path is required.");
    const workspaceRoot = ensureRuntimeWorkspace();
    const absolutePath = path.resolve(workspaceRoot, relativePath);
    if (absolutePath !== workspaceRoot && !absolutePath.startsWith(`${workspaceRoot}${path.sep}`)) {
      throw new Error("Path escapes runtime workspace.");
    }
    shell.showItemInFolder(absolutePath);
    return { ok: true, path: relativePath };
  }

  if (cmd === "run_auto_task_now") {
    const taskId = Number(args.taskId);
    if (!Number.isFinite(taskId)) throw new Error("taskId is required.");
    if (!scheduler) throw new Error("Scheduler is not running.");
    scheduler.runOnce(taskId).catch((err) => log("scheduler", "manual run failed", { error: err instanceof Error ? err.message : String(err) }));
    return { ok: true, taskId };
  }

  throw new Error(`Unhandled main command: ${cmd}`);
}

app.whenReady().then(() => {
  session.defaultSession.setPermissionRequestHandler((_webContents, permission, callback) => {
    callback(permission === "media");
  });
  session.defaultSession.setPermissionCheckHandler((_webContents, permission) => {
    return permission === "media";
  });

  const workspaceRoot = ensureRuntimeWorkspace();
  initLogger(workspaceRoot);
  host = new PythonHost(workspaceRoot);
  host.onEvent((event) => {
    mainWindow?.webContents.send("aios:host-event", event);
  });
  host.start();
  scheduler = new AutoTaskScheduler(host);
  scheduler.start();

  ipcMain.handle("aios:invoke", async (_event, cmd: AiosCommand, args: Record<string, unknown> = {}) => {
    try {
      if (mainHandledCommands.has(cmd)) {
        return { ok: true, data: await handleMainCommand(cmd, args) };
      }

      const response = await host?.invoke(cmd, args);
      if (!response) return { ok: false, error: { code: "HOST_MISSING", message: "Python host is not running." } };
      return response.ok ? { ok: true, data: response.data } : { ok: false, error: response.error };
    } catch (error) {
      log("main.ipc", "command failed", { cmd, error: error instanceof Error ? error.message : String(error) });
      return {
        ok: false,
        error: {
          code: "MAIN_ERROR",
          message: error instanceof Error ? error.message : String(error)
        }
      };
    }
  });

  createWindow();

  // Auto-update from GitHub Releases. Only checks in packaged builds —
  // electron-updater no-ops in dev. We let it download silently in the
  // background; users get the new version on next launch.
  if (app.isPackaged) {
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    const broadcast = (state: string, payload?: Record<string, unknown>) => {
      mainWindow?.webContents.send("aios:update-state", { state, ...payload });
    };

    autoUpdater.on("checking-for-update", () => broadcast("checking"));
    autoUpdater.on("update-available", (info) => {
      log("updater", "update-available", { version: info.version });
      broadcast("available", { version: info.version });
    });
    autoUpdater.on("update-not-available", (info) => broadcast("up-to-date", { version: info.version }));
    autoUpdater.on("download-progress", (p) => broadcast("downloading", { percent: Math.round(p.percent) }));
    autoUpdater.on("update-downloaded", (info) => {
      log("updater", "update-downloaded", { version: info.version });
      broadcast("ready", { version: info.version });
    });
    autoUpdater.on("error", (err) => {
      log("updater", "error", { error: err.message });
      broadcast("error", { message: err.message });
    });

    autoUpdater.checkForUpdatesAndNotify().catch((err) => log("updater", "check-failed", { error: err?.message }));
  }

  // IPC: returns the currently-running app's version (from package.json).
  ipcMain.handle("aios:get-version", () => app.getVersion());

  // IPC: manual "Check for updates" trigger from Settings.
  ipcMain.handle("aios:check-for-updates", async () => {
    if (!app.isPackaged) {
      return { ok: false, reason: "not-packaged", currentVersion: app.getVersion() };
    }
    try {
      const result = await autoUpdater.checkForUpdates();
      return {
        ok: true,
        currentVersion: app.getVersion(),
        latestVersion: result?.updateInfo?.version ?? app.getVersion(),
        hasUpdate: !!result?.updateInfo && result.updateInfo.version !== app.getVersion()
      };
    } catch (err) {
      return { ok: false, reason: "check-failed", error: err instanceof Error ? err.message : String(err) };
    }
  });

  // IPC: install the downloaded update + restart.
  ipcMain.handle("aios:install-update", async () => {
    if (!app.isPackaged) return { ok: false, reason: "not-packaged" };
    try {
      autoUpdater.quitAndInstall();
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

let isCleaningUp = false;
app.on("before-quit", (event) => {
  if (isCleaningUp) return;
  isCleaningUp = true;
  event.preventDefault();
  scheduler?.stop();
  // host.stop() may be async — fire it, then exit on settle. Give it a 1.5s
  // ceiling so a wedged Python sidecar can't keep the app from quitting.
  const stopHost = Promise.resolve(host?.stop()).catch(() => undefined);
  const watchdog = new Promise<void>((resolve) => setTimeout(resolve, 1500));
  Promise.race([stopHost, watchdog]).finally(() => app.exit(0));
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
