import path from "node:path";
import { app, BrowserWindow, dialog, ipcMain, shell, globalShortcut, session } from "electron";
import { autoUpdater } from "electron-updater";
import type { AiosCommand } from "./types";
import { findClaude, validateClaude } from "./claude-finder";
import { initLogger, log } from "./logger";
import { PythonHost } from "./python-host";
import { AutoTaskScheduler } from "./scheduler";
import { ensureRuntimeWorkspace, getSourceStarterKit, backfillStarterKit } from "./workspace";
import { startWhatsApp, stopWhatsApp, getWhatsAppStatus, autoStartWhatsApp } from "./whatsapp-scanner";
import { startVoiceLoop, abortVoiceLoop, getVoiceState } from "./voice-control";
import {
  installControlPopupHooks,
  toggleControlPopup,
  openControlPopup,
  closeControlPopup,
  destroyControlPopup,
  isPanelDocked,
  setPanelDocked,
  getControlPopup,
} from "./control-popup";
import {
  installControlBubbleHooks,
  showControlBubble,
  hideControlBubble,
  toggleControlBubble,
  destroyControlBubble,
  isBubbleVisible,
  beginBubbleDrag,
  endBubbleDrag,
} from "./control-bubble";
import {
  isCursorOverlayActive,
  setCursorOverlayActive,
  destroyCursorOverlay,
  getCursorColor,
  setCursorColor,
  flyCursorTo,
  showCursorMessage,
  setCursorBusy,
  setCursorOverlayHost,
} from "./cursor-overlay";

let mainWindow: BrowserWindow | null = null;
let host: PythonHost | null = null;
let scheduler: AutoTaskScheduler | null = null;

// Every BrowserWindow that should receive 'aios:host-event' broadcasts.
// Today: the main window + (lazily) the Control popup window. Adding
// new event-listening windows just registers them here.
const eventSubscribers = new Set<BrowserWindow>();
function broadcastHostEvent(event: unknown): void {
  for (const win of eventSubscribers) {
    if (!win.isDestroyed()) {
      try { win.webContents.send("aios:host-event", event); } catch { /* renderer might be reloading */ }
    }
  }
}

app.setName("aios-desktop");
app.setAppUserModelId("com.aios.desktop");
if (!app.isPackaged) {
  app.disableHardwareAcceleration();
  app.commandLine.appendSwitch("disable-gpu");
  app.commandLine.appendSwitch("disable-gpu-compositing");
  app.commandLine.appendSwitch("in-process-gpu");
  app.commandLine.appendSwitch("disable-features", "VizDisplayCompositor");
  app.setPath("userData", path.join(process.cwd(), ".aios-dev-user-data"));
}

const mainHandledCommands = new Set<AiosCommand>([
  "find_claude",
  "set_claude_path",
  "test_claude_connection",
  "reveal_in_file_manager",
  "run_auto_task_now",
  "whatsapp_status",
  "whatsapp_start",
  "whatsapp_stop",
  "export_to_pdf",
  "install_claude",
  "open_claude_login_terminal",
  "voice_control_start",
  "voice_control_stop",
  "voice_control_abort",
  "voice_control_state",
  "control_panel_toggle",
  "control_panel_open",
  "control_panel_close",
  "control_bubble_toggle",
  "control_bubble_show",
  "control_bubble_hide",
  "control_bubble_drag_start",
  "control_bubble_drag_to",
  "control_bubble_drag_end",
  "control_panel_get_docked",
  "control_panel_set_docked",
  "cursor_overlay_get_active",
  "cursor_overlay_set_active",
  "cursor_overlay_get_color",
  "cursor_overlay_set_color",
  "control_close_all",
  "control_open_settings"
]);

// Theme cache lives in userData so the main process can pick the right
// backgroundColor BEFORE the renderer (and its localStorage) is loaded.
// Without this, dark-theme users see ~100ms of light paper before HTML
// parses and the inline boot splash applies dark tokens.
function getThemeCachePath(): string {
  return path.join(app.getPath("userData"), "theme-cache.txt");
}

function readCachedTheme(): "light" | "dark" | "auto" {
  try {
    const fs = require("fs");
    const raw = fs.readFileSync(getThemeCachePath(), "utf8").trim().toLowerCase();
    if (raw === "dark" || raw === "auto") return raw;
    return "light";
  } catch {
    return "light";
  }
}

function writeCachedTheme(value: string): void {
  try {
    const fs = require("fs");
    const normalized = value === "dark" || value === "auto" ? value : "light";
    fs.mkdirSync(path.dirname(getThemeCachePath()), { recursive: true });
    fs.writeFileSync(getThemeCachePath(), normalized, "utf8");
  } catch { /* best-effort */ }
}

function backgroundForTheme(theme: "light" | "dark" | "auto"): string {
  if (theme === "dark") return "#0d0d0d";
  if (theme === "auto") {
    const { nativeTheme } = require("electron");
    return nativeTheme?.shouldUseDarkColors ? "#0d0d0d" : "#fafaf7";
  }
  return "#fafaf7";
}

function createWindow(): void {
  // Resolve the icon if it exists (generated by `node assets/generate-icons.js`).
  const iconPath = path.join(__dirname, "..", "..", "assets", "icon.png");
  const fs = require("fs");
  const icon = fs.existsSync(iconPath) ? iconPath : undefined;

  // On Mac use "hiddenInset" so the system traffic-light buttons stay visible
  // (inset into our drag region). On Windows we keep the chromeless look and
  // render our own minimize/maximize/close controls in the renderer.
  const isMac = process.platform === "darwin";
  const cachedTheme = readCachedTheme();
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1040,
    minHeight: 720,
    title: "AIOS Desktop",
    frame: !isMac ? false : undefined,
    backgroundColor: backgroundForTheme(cachedTheme),
    titleBarStyle: isMac ? "hiddenInset" : "hidden",
    trafficLightPosition: isMac ? { x: 18, y: 18 } : undefined,
    icon,
    // Show the window IMMEDIATELY on creation. Earlier we used `show: false`
    // + `ready-to-show` to avoid a brief flash before the renderer painted,
    // but on a cold first launch the renderer can take 2–5 s to produce its
    // first frame — meaning the user saw no window at all after double-
    // clicking the icon, which felt broken. With `backgroundColor` already
    // set to the paper sage, Electron paints the window in the right color
    // the instant it appears, and the inline boot splash in `index.html`
    // takes over a moment later once the renderer loads its HTML. Net effect:
    // the user sees a window confirming their click immediately.
    show: true,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  });

  const devUrl = process.env.VITE_DEV_SERVER_URL;
  if (devUrl) {
    mainWindow.loadURL(devUrl);
  } else {
    mainWindow.loadFile(path.join(__dirname, "..", "renderer", "index.html"));
  }

  // Route every link click / window.open / target=_blank that the renderer
  // emits into the user's default system browser. Without this, Electron
  // either replaces the app window with the destination page or pops up an
  // ugly bare BrowserWindow. The OAuth flow has its own explicit IPC
  // (aios:open-external + aios:open-oauth-window) and isn't affected.
  const internalOrigins = new Set<string>();
  if (devUrl) internalOrigins.add(new URL(devUrl).origin);

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//i.test(url) || /^mailto:/i.test(url)) {
      void shell.openExternal(url);
    }
    return { action: "deny" };
  });

  mainWindow.webContents.on("will-navigate", (event, url) => {
    try {
      const target = new URL(url);
      // Allow same-origin SPA navigation (Vite HMR, route changes inside the
      // renderer); push everything else to the system browser.
      if (target.protocol === "file:" || internalOrigins.has(target.origin)) return;
      event.preventDefault();
      if (target.protocol === "http:" || target.protocol === "https:" || target.protocol === "mailto:") {
        void shell.openExternal(url);
      }
    } catch {
      event.preventDefault();
    }
  });

  mainWindow.on("maximize", () => {
    if (!mainWindow?.isDestroyed()) mainWindow?.webContents.send("window:maximized-changed", true);
  });
  mainWindow.on("unmaximize", () => {
    if (!mainWindow?.isDestroyed()) mainWindow?.webContents.send("window:maximized-changed", false);
  });
  mainWindow.on("closed", () => {
    if (mainWindow) eventSubscribers.delete(mainWindow);
    mainWindow = null;
  });

  // Register main window as an aios:host-event subscriber so broadcasts
  // reach it the same way they reach the Control popup.
  eventSubscribers.add(mainWindow);

  // Auto-show the Computer Control bubble shortly after the main window
  // appears. Small delay so it doesn't pop up during the inline boot
  // splash + before the renderer paints — feels more deliberate. User
  // can still toggle it off via the sidebar Control button or panel Quit.
  setTimeout(() => {
    try { showControlBubble(); } catch { /* non-fatal */ }
  }, 1500);
}

function registerIpcHandlers(): void {
  // Window control IPC handlers
  ipcMain.on("window:minimize", () => mainWindow?.minimize());
  ipcMain.on("window:maximize", () => {
    if (mainWindow?.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow?.maximize();
    }
  });
  ipcMain.on("window:close", () => mainWindow?.close());

  // Open URL in the OS default browser (used for help/docs links).
  if (ipcMain.handle) {
    ipcMain.removeHandler("aios:cache-theme");
    ipcMain.handle("aios:cache-theme", async (_event, theme: string) => {
      if (typeof theme !== "string") return { ok: false };
      writeCachedTheme(theme);
      return { ok: true };
    });

    ipcMain.removeHandler("aios:open-external");
    ipcMain.handle("aios:open-external", async (_event, url: string) => {
      if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
      if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };
      try {
        await shell.openExternal(url);
        return { ok: true };
      } catch (err) {
        return { ok: false, error: err instanceof Error ? err.message : String(err) };
      }
    });

    ipcMain.removeHandler("aios:open-oauth-window");
    ipcMain.handle("aios:open-oauth-window", async (_event, url: string) => {
      if (typeof url !== "string") return { ok: false, error: "URL must be a string" };
      if (!/^https?:\/\//i.test(url)) return { ok: false, error: "Only http/https URLs are allowed" };

      const partition = `oauth-${Date.now()}`;
      const oauthSession = session.fromPartition(partition);
      try {
        await oauthSession.clearStorageData();
      } catch { /* fresh partition is already empty */ }

      // Force Google's OAuth flow to show the account picker every time
      oauthSession.webRequest.onBeforeRequest(
        { urls: ["https://accounts.google.com/o/oauth2/*"] },
        (details, callback) => {
          try {
            const url = new URL(details.url);
            if (
              (url.pathname.startsWith("/o/oauth2/v2/auth") || url.pathname.startsWith("/o/oauth2/auth")) &&
              !url.searchParams.has("prompt")
            ) {
              url.searchParams.set("prompt", "select_account");
              callback({ redirectURL: url.toString() });
              return;
            }
          } catch { /* fall through */ }
          callback({});
        }
      );

      return await new Promise<{ ok: boolean; completed?: boolean; error?: string }>((resolve) => {
        const win = new BrowserWindow({
          width: 540,
          height: 720,
          title: "Connect account",
          parent: mainWindow ?? undefined,
          modal: false,
          autoHideMenuBar: true,
          backgroundColor: "#fafaf7",
          webPreferences: {
            session: oauthSession,
            contextIsolation: true,
            nodeIntegration: false,
            sandbox: true,
            enableWebSQL: false,
          },
        });

        let resolved = false;
        const safeResolve = (payload: { ok: boolean; completed?: boolean; error?: string }) => {
          if (resolved) return;
          resolved = true;
          resolve(payload);
        };

        win.on("closed", () => {
          safeResolve({ ok: true, completed: false });
        });

        win.loadURL(url).catch((err: unknown) => {
          safeResolve({
            ok: false,
            error: err instanceof Error ? err.message : String(err),
          });
          try { win.close(); } catch { /* noop */ }
        });
      });
    });
  }

  // Global shortcut for preferences
  globalShortcut.register("Command+,", () => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("shortcut:preferences");
    }
  });

  // Global shortcut for Computer Control mic — works from any app on
  // the desktop. Different chord per OS because the modifier
  // ergonomics differ:
  //   Windows: Ctrl + Alt + V         (left hand thumb + index)
  //   macOS:   Cmd + Ctrl + V         (TipTour parity, doesn't clash
  //                                    with Cmd+Option+V "paste-as-
  //                                    plain-text" Mac shortcut)
  // Pressing the chord:
  //   1. Shows the bubble if it isn't already
  //   2. Opens the popup (or focuses if open)
  //   3. Fires `shortcut:voice-toggle` into the popup so the panel
  //      starts mic capture immediately (or stops it if listening).
  // End result: user can press the chord from any app and start
  // talking right away.
  const voiceShortcut = process.platform === "darwin"
    ? "Command+Control+V"
    : "Control+Alt+V";
  const voiceShortcutRegistered = globalShortcut.register(voiceShortcut, () => {
    if (!isBubbleVisible()) showControlBubble();
    // Make sure the popup is OPEN (not just toggled) before we tell
    // the panel to start listening — otherwise we'd start a voice
    // session in a hidden popup.
    openControlPopup();
    const popup = getControlPopup();
    if (popup && !popup.isDestroyed()) {
      // Tiny defer so the popup's renderer is mounted + subscribed to
      // the voice-toggle event when it arrives. Without this the
      // first press after-launch sometimes misses the listener.
      setTimeout(() => {
        if (!popup.isDestroyed()) popup.webContents.send("shortcut:voice-toggle");
      }, 80);
    }
  });
  if (!voiceShortcutRegistered) {
    log("shortcut", "voice-register-failed", { chord: voiceShortcut });
  }
}


async function getSavedClaudePath(): Promise<string | null> {
  const response = await host?.invoke<{ value: string | null }>("get_setting", { key: "claude_path" });
  return response?.ok ? response.data?.value ?? null : null;
}

async function handleMainCommand(cmd: AiosCommand, args: Record<string, unknown>) {
  if (!host) throw new Error("Python host not initialized");

  if (cmd === "find_claude") {
    const savedPath = await getSavedClaudePath();
    const result = await findClaude(savedPath);
    if (result.found && result.path) {
      await host.invoke("set_setting", { key: "claude_path", value: result.path });
      await host.invoke("set_setting", { key: "claude_version", value: result.version ?? "" });
    }
    return result;
  }

  if (cmd === "set_claude_path") {
    let selectedPath = String(args.path ?? "");
    if (!selectedPath && args.browse === true) {
      const result = await dialog.showOpenDialog({
        title: "Select Claude Code executable",
        properties: ["openFile"]
      });
      selectedPath = result.filePaths[0] ?? "";
    }
    const validation = await validateClaude(selectedPath);
    if (!validation.ok) {
      return { stored: false, ...validation };
    }
    await host.invoke("set_setting", { key: "claude_path", value: selectedPath });
    await host.invoke("set_setting", { key: "claude_version", value: validation.version ?? "" });
    return { stored: true, path: selectedPath, version: validation.version };
  }

  if (cmd === "test_claude_connection") {
    const pathArg = typeof args.path === "string" ? args.path : await getSavedClaudePath();
    if (!pathArg) return { ok: false, version: null, error: "Claude path is not configured." };
    const validation = await validateClaude(pathArg);
    return { ok: validation.ok, path: pathArg, version: validation.version, error: validation.error };
  }

  if (cmd === "reveal_in_file_manager") {
    const relativePath = String(args.path ?? "");
    if (!relativePath) throw new Error("Path is required.");
    const workspaceRoot = ensureRuntimeWorkspace();
    const absolutePath = path.resolve(workspaceRoot, relativePath);
    if (absolutePath !== workspaceRoot && !absolutePath.startsWith(`${workspaceRoot}${path.sep}`)) {
      throw new Error("Path escapes runtime workspace.");
    }
    shell.showItemInFolder(absolutePath);
    return { ok: true, path: relativePath };
  }

  if (cmd === "run_auto_task_now") {
    const taskId = Number(args.taskId);
    if (!Number.isFinite(taskId)) throw new Error("taskId is required.");
    if (!scheduler) throw new Error("Scheduler is not running.");
    scheduler.runOnce(taskId).catch((err) => log("scheduler", "manual run failed", { error: err instanceof Error ? err.message : String(err) }));
    return { ok: true, taskId };
  }

  if (cmd === "whatsapp_status") {
    return getWhatsAppStatus();
  }

  if (cmd === "whatsapp_start") {
    if (!mainWindow) throw new Error("No main window");
    return await startWhatsApp(host, mainWindow);
  }

  if (cmd === "whatsapp_stop") {
    if (!mainWindow) throw new Error("No main window");
    return await stopWhatsApp(mainWindow);
  }

  if (cmd === "voice_control_start") {
    const transcript = String(args.transcript ?? "").trim();
    const claudePath = String(args.claudePath ?? "");
    const maxTurnsArg = Number(args.maxTurns);
    const maxTurns = Number.isFinite(maxTurnsArg) ? maxTurnsArg : undefined;
    if (!transcript) throw new Error("transcript is required");
    if (!claudePath) throw new Error("claudePath is required");
    // Fire and forget — the loop streams state via 'aios:host-event' channel
    // so the renderer doesn't have to block on this IPC for the full run.
    startVoiceLoop({ transcript, claudePath, host, broadcast: broadcastHostEvent, maxTurns }).catch((err) => {
      log("voice", "loop failed", { error: err instanceof Error ? err.message : String(err) });
    });
    return { ok: true, accepted: true };
  }

  if (cmd === "voice_control_stop" || cmd === "voice_control_abort") {
    await abortVoiceLoop(broadcastHostEvent);
    return { ok: true };
  }

  if (cmd === "voice_control_state") {
    return { state: getVoiceState() };
  }

  if (cmd === "control_panel_toggle") {
    toggleControlPopup();
    return { ok: true };
  }
  if (cmd === "control_panel_open") {
    openControlPopup();
    return { ok: true };
  }
  if (cmd === "control_panel_close") {
    closeControlPopup();
    return { ok: true };
  }
  if (cmd === "control_bubble_toggle") {
    // Toggling the bubble off should also hide the panel — the panel is
    // a popover anchored to the bubble; without the bubble it would be
    // orphaned.
    const wasVisible = isBubbleVisible();
    toggleControlBubble();
    if (wasVisible) closeControlPopup();
    return { ok: true };
  }
  if (cmd === "control_bubble_show") {
    showControlBubble();
    return { ok: true };
  }
  if (cmd === "control_bubble_hide") {
    hideControlBubble();
    closeControlPopup();
    return { ok: true };
  }
  // Manual drag IPCs — replaced `-webkit-app-region: drag` (the OS
  // native drag intercepted clicks in Electron 39+ and the panel toggle
  // stopped firing). Main polls screen.getCursorScreenPoint() at 60Hz
  // between drag_start and drag_end to move the bubble — renderer-side
  // pointermove tracking broke because the bubble window is 56×56 and
  // the cursor escapes it as soon as the user moves faster than the
  // bubble can follow. We accept no coordinates on drag_to because
  // main reads cursor position itself.
  if (cmd === "control_bubble_drag_start") {
    beginBubbleDrag();
    return { ok: true };
  }
  if (cmd === "control_bubble_drag_to") {
    // No-op: kept for API stability (renderer might call it during
    // transitional builds). Main is already polling the cursor.
    return { ok: true };
  }
  if (cmd === "control_bubble_drag_end") {
    endBubbleDrag();
    return { ok: true };
  }
  if (cmd === "control_panel_get_docked") {
    return { docked: isPanelDocked() };
  }
  if (cmd === "control_panel_set_docked") {
    const docked = !!args.docked;
    setPanelDocked(docked);
    return { ok: true, docked };
  }
  if (cmd === "cursor_overlay_get_active") {
    return { active: isCursorOverlayActive() };
  }
  if (cmd === "cursor_overlay_set_active") {
    const next = !!args.active;
    setCursorOverlayActive(next);
    return { ok: true, active: next };
  }
  if (cmd === "cursor_overlay_get_color") {
    return { color: getCursorColor() };
  }
  if (cmd === "cursor_overlay_set_color") {
    const color = typeof args.color === "string" ? args.color : "#9caf9b";
    setCursorColor(color);
    return { ok: true, color };
  }
  if (cmd === "control_close_all") {
    // "Quit Control" — full exit from Computer Control mode. Aborts any
    // in-flight voice loop, closes the panel, hides the bubble, turns off
    // the cursor companion. Doesn't quit AIOS itself; user re-enters via
    // the sidebar Control button.
    await abortVoiceLoop(broadcastHostEvent);
    closeControlPopup();
    hideControlBubble();
    setCursorOverlayActive(false);
    return { ok: true };
  }
  if (cmd === "control_open_settings") {
    // Focus the main AIOS window and route it to the Settings screen so
    // the user can configure Claude / theme / etc.
    if (mainWindow && !mainWindow.isDestroyed()) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.show();
      mainWindow.focus();
      mainWindow.webContents.send("shortcut:preferences");
    }
    return { ok: true };
  }

  if (cmd === "install_claude") {
    // Run the official Claude Code standalone installer script. Picks a
    // platform-appropriate one-liner — both install a self-contained binary,
    // no Node / npm prerequisite. Streams stdout/stderr back to the renderer
    // via `aios:host-event` so the onboarding card can show a live log tail.
    //
    // Refs:
    //   Mac/Linux: curl -fsSL https://claude.ai/install.sh | bash
    //   Windows  : irm https://claude.ai/install.ps1 | iex   (PowerShell)
    const { spawn } = require("child_process");
    const isWin = process.platform === "win32";
    const program = isWin ? "powershell.exe" : "bash";
    const args = isWin
      ? [
          "-NoProfile",
          "-ExecutionPolicy",
          "Bypass",
          "-Command",
          "irm https://claude.ai/install.ps1 | iex",
        ]
      : ["-c", "curl -fsSL https://claude.ai/install.sh | bash"];

    const emit = (line: string) => {
      if (!mainWindow || mainWindow.isDestroyed()) return;
      mainWindow.webContents.send("aios:host-event", {
        id: "claude-install",
        event: "claude_install_log",
        data: { line },
      });
    };

    const logs: string[] = [];
    return await new Promise<{ ok: boolean; error?: string; logs: string[] }>((resolve) => {
      let child: ReturnType<typeof spawn>;
      try {
        child = spawn(program, args, { shell: false, windowsHide: true });
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        resolve({ ok: false, error: `Could not start ${program}: ${message}`, logs });
        return;
      }
      const pushLine = (chunk: Buffer | string) => {
        const text = String(chunk);
        logs.push(text);
        // Send the chunk as-is — the renderer splits on newlines for display.
        emit(text);
      };
      child.stdout?.on("data", pushLine);
      child.stderr?.on("data", pushLine);
      child.on("error", (err: Error) => {
        resolve({ ok: false, error: err.message, logs });
      });
      child.on("close", (code: number | null) => {
        if (code === 0) {
          resolve({ ok: true, logs });
        } else {
          resolve({
            ok: false,
            error: `Installer exited with code ${code ?? "unknown"}.`,
            logs,
          });
        }
      });
    });
  }

  if (cmd === "open_claude_login_terminal") {
    // Pop a native terminal window running `claude /login` — the explicit
    // login slash command. Goes straight to the OAuth / API-key picker
    // instead of dropping the user into the REPL first. We can't drive the
    // browser flow from a non-TTY subprocess reliably, so we hand off to the
    // OS terminal and rely on the user clicking "I've signed in" once done.
    const { spawn } = require("child_process");
    try {
      if (process.platform === "win32") {
        // `start` is a cmd builtin, not an exe — wrap with cmd /c. /K keeps
        // the new window open after `claude /login` exits so the user can
        // read any post-login output.
        spawn("cmd.exe", ["/c", "start", "", "cmd.exe", "/K", "claude /login"], {
          detached: true,
          stdio: "ignore",
          windowsHide: false,
        }).unref();
      } else if (process.platform === "darwin") {
        spawn("osascript", [
          "-e",
          'tell application "Terminal" to do script "claude /login"',
          "-e",
          'tell application "Terminal" to activate',
        ], { detached: true, stdio: "ignore" }).unref();
      } else {
        // Linux desktops vary wildly. Try x-terminal-emulator first; if it
        // isn't present, fall back to common terminals.
        const candidates = ["x-terminal-emulator", "gnome-terminal", "konsole", "xterm"];
        let opened = false;
        for (const term of candidates) {
          try {
            spawn(term, ["-e", "claude /login"], { detached: true, stdio: "ignore" }).unref();
            opened = true;
            break;
          } catch {
            /* try next */
          }
        }
        if (!opened) {
          return { ok: false, error: "Could not find a terminal emulator to open. Run `claude /login` manually." };
        }
      }
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  if (cmd === "export_to_pdf") {
    // Render arbitrary markdown (passed by the renderer or by the agent via
    // the [AIOS_EXPORT_PDF: ...] marker pipeline) to a PDF in the workspace's
    // outputs/ folder. Returns the workspace-relative path so the chat
    // attachment chip can deep-link via the existing pendingAttachmentOpen
    // flow in App.tsx.
    const markdown = typeof args.markdown === "string" ? args.markdown : "";
    if (!markdown.trim()) throw new Error("markdown is required.");
    const requestedFilename = typeof args.filename === "string" ? args.filename : "";
    const slug = (requestedFilename || `export-${Date.now()}`)
      .replace(/\.pdf$/i, "")
      .replace(/[^A-Za-z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || `export-${Date.now()}`;
    const filename = `${slug}.pdf`;
    const workspaceRoot = ensureRuntimeWorkspace();
    const outputsDir = path.join(workspaceRoot, "outputs");
    const outputPath = path.join(outputsDir, filename);
    const { renderMarkdownStringToPdf } = await import("./pdf-export");
    await renderMarkdownStringToPdf({
      markdown,
      outputPath,
      title: slug,
      parentWindow: mainWindow,
    });
    return { ok: true, path: `outputs/${filename}`, filename };
  }

  throw new Error(`Unhandled main command: ${cmd}`);
}

app.whenReady().then(() => {
  session.defaultSession.setPermissionRequestHandler((_webContents, permission, callback) => {
    callback(permission === "media");
  });
  session.defaultSession.setPermissionCheckHandler((_webContents, permission) => {
    return permission === "media";
  });

  const workspaceRoot = ensureRuntimeWorkspace();
  const starterKitRoot = getSourceStarterKit();
  initLogger(workspaceRoot);
  host = new PythonHost(workspaceRoot, starterKitRoot);
  host.onEvent((event) => {
    broadcastHostEvent(event);
    // Modifier-only voice shortcut: when the Python sidecar's
    // Mac CGEventTap detects a clean Cmd+Ctrl tap (both held + both
    // released without any other key pressed in between), it
    // broadcasts a `voice_shortcut_triggered` event. We treat this
    // the same as the keyboard-accelerator global shortcut: show
    // bubble, open popup, fire shortcut:voice-toggle to start mic.
    // The Python listener is Mac-only (CGEventTap is macOS API);
    // Windows users still rely on the Ctrl+Alt+V Electron shortcut.
    const evtName = (event as { event?: string } | null)?.event;
    if (evtName === "voice_shortcut_triggered") {
      if (!isBubbleVisible()) showControlBubble();
      openControlPopup();
      const popup = getControlPopup();
      if (popup && !popup.isDestroyed()) {
        setTimeout(() => {
          if (!popup.isDestroyed()) popup.webContents.send("shortcut:voice-toggle");
        }, 80);
      }
    }
  });
  setCursorOverlayHost(host);

  // Register the Control popup + Control bubble as event subscribers the
  // moment each is created. Both hide instead of destroying on close, but
  // if they do get destroyed (app quit, force-close) we drop them from
  // the set.
  installControlPopupHooks({
    subscribe: (win) => { eventSubscribers.add(win); },
    unsubscribe: (win) => { eventSubscribers.delete(win); },
  });
  installControlBubbleHooks({
    subscribe: (win) => { eventSubscribers.add(win); },
    unsubscribe: (win) => { eventSubscribers.delete(win); },
  });
  let hostStarted = false;
  try {
    host.start();
    hostStarted = true;
  } catch (error) {
    log("python", "host failed to start", { error: error instanceof Error ? error.message : String(error) });
  }
  scheduler = new AutoTaskScheduler(host);
  if (hostStarted) scheduler.start();

  ipcMain.handle("aios:invoke", async (_event, cmd: AiosCommand, args: Record<string, unknown> = {}) => {
    try {
      if (mainHandledCommands.has(cmd)) {
        return { ok: true, data: await handleMainCommand(cmd, args) };
      }

      const response = await host?.invoke(cmd, args);
      if (!response) return { ok: false, error: { code: "HOST_MISSING", message: "Python host is not running." } };
      return response.ok ? { ok: true, data: response.data } : { ok: false, error: response.error };
    } catch (error) {
      log("main.ipc", "command failed", { cmd, error: error instanceof Error ? error.message : String(error) });
      return {
        ok: false,
        error: {
          code: "MAIN_ERROR",
          message: error instanceof Error ? error.message : String(error)
        }
      };
    }
  });

  registerIpcHandlers();
  createWindow();

  // Run the starter-kit copy / infra resync AFTER the window is on screen.
  // ensureRuntimeWorkspace() above only set up data/ and logs/ — the heavier
  // copy work happens here so it can't block the boot critical path.
  if (mainWindow) {
    mainWindow.once("ready-to-show", () => {
      setImmediate(() => backfillStarterKit());
    });
    // Fallback in case ready-to-show is somehow not emitted within 2 s.
    setTimeout(() => backfillStarterKit(), 2000);
  } else {
    backfillStarterKit();
  }

  if (host && mainWindow) {
    autoStartWhatsApp(host, mainWindow);
  }

  const broadcast = (state: string, payload?: Record<string, unknown>) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("aios:update-state", { state, ...payload });
    }
  };

  // electron-updater's in-place auto-update works on both Windows and macOS
  // now that we ship Apple Developer ID-signed + notarized .app bundles
  // (since v0.2.7). Squirrel.Mac validates the new bundle's signature
  // against the running app's signature before swapping — both are signed
  // with the same SAPHAARE LABS Developer ID, so the swap succeeds.
  //
  // Previously this block was gated to `!isMac` because earlier Mac builds
  // were unsigned and ShipIt threw "code failed to satisfy specified code
  // requirement(s)". Removing that gate lets Mac users get the same
  // background-download + restart-to-install flow Windows users already had.
  const isMac = process.platform === "darwin";

  if (app.isPackaged) {
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    autoUpdater.on("checking-for-update", () => broadcast("checking"));
    autoUpdater.on("update-available", (info) => {
      log("updater", "update-available", { version: info.version });
      broadcast("available", { version: info.version });
    });
    autoUpdater.on("update-not-available", (info) => broadcast("up-to-date", { version: info.version }));
    autoUpdater.on("download-progress", (p) => broadcast("downloading", { percent: Math.round(p.percent) }));
    autoUpdater.on("update-downloaded", (info) => {
      log("updater", "update-downloaded", { version: info.version });
      broadcast("ready", { version: info.version });
    });
    autoUpdater.on("error", (err) => {
      log("updater", "error", { error: err.message });
      broadcast("error", { message: err.message });
    });

    autoUpdater.checkForUpdatesAndNotify().catch((err) => log("updater", "check-failed", { error: err?.message }));
  }

  // Compare semver-like versions: returns true if `latest` is strictly newer
  // than `current`. Stripping a leading "v" lets us compare GH tag names
  // ("v0.1.9") against package.json versions ("0.1.9") interchangeably.
  function isNewerVersion(latest: string, current: string): boolean {
    const parse = (v: string) => v.replace(/^v/i, "").split(/[.-]/).map((n) => Number(n) || 0);
    const lp = parse(latest);
    const cp = parse(current);
    for (let i = 0; i < Math.max(lp.length, cp.length); i++) {
      const l = lp[i] ?? 0;
      const c = cp[i] ?? 0;
      if (l > c) return true;
      if (l < c) return false;
    }
    return false;
  }

  // Mac-only manual update check: query GitHub's releases/latest endpoint
  // (no auth required for public repos), compare versions, broadcast a
  // "manual-available" state with the release URL when newer.
  async function checkForUpdatesManual(): Promise<{
    ok: boolean;
    currentVersion: string;
    latestVersion?: string;
    hasUpdate?: boolean;
    manualDownloadUrl?: string;
    reason?: string;
    error?: string;
  }> {
    const currentVersion = app.getVersion();
    try {
      broadcast("checking");
      const res = await fetch(
        "https://api.github.com/repos/satyaprakashmallidi/AIOS_Desktop/releases/latest",
        { headers: { Accept: "application/vnd.github+json", "User-Agent": "AIOS-Desktop" } }
      );
      if (!res.ok) {
        broadcast("error", { message: `GitHub API ${res.status}` });
        return { ok: false, currentVersion, reason: "check-failed", error: `GitHub API ${res.status}` };
      }
      const data = (await res.json()) as { tag_name?: string; html_url?: string };
      const tag = data.tag_name ?? "";
      const latestVersion = tag.replace(/^v/i, "");
      const url = data.html_url ?? `https://github.com/satyaprakashmallidi/AIOS_Desktop/releases/latest`;
      if (isNewerVersion(latestVersion, currentVersion)) {
        broadcast("manual-available", { version: latestVersion, manualDownloadUrl: url });
        return { ok: true, currentVersion, latestVersion, hasUpdate: true, manualDownloadUrl: url };
      }
      broadcast("up-to-date", { version: currentVersion });
      return { ok: true, currentVersion, latestVersion, hasUpdate: false };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      broadcast("error", { message });
      return { ok: false, currentVersion, reason: "check-failed", error: message };
    }
  }

  // IPC: returns the currently-running app's version (from package.json).
  ipcMain.handle("aios:get-version", () => app.getVersion());

  // IPC: manual "Check for updates" trigger from Settings.
  // Both Mac and Windows go through electron-updater now that Mac builds
  // are signed + notarized. The `checkForUpdatesManual` GitHub-API fallback
  // is kept as the error path: if electron-updater fails for any reason
  // (unsigned dev build, latest-mac.yml missing on a release, etc.) we
  // gracefully degrade to the "open release page in browser" UX rather
  // than leaving the user stranded.
  ipcMain.handle("aios:check-for-updates", async () => {
    if (!app.isPackaged) {
      return { ok: false, reason: "not-packaged", currentVersion: app.getVersion() };
    }
    try {
      const result = await autoUpdater.checkForUpdates();
      return {
        ok: true,
        currentVersion: app.getVersion(),
        latestVersion: result?.updateInfo?.version ?? app.getVersion(),
        hasUpdate: !!result?.updateInfo && result.updateInfo.version !== app.getVersion()
      };
    } catch (err) {
      // Fall back to the manual-download path on the off-chance
      // electron-updater fails. Better than a hard error.
      if (isMac) return await checkForUpdatesManual();
      return { ok: false, reason: "check-failed", error: err instanceof Error ? err.message : String(err) };
    }
  });

  // IPC: install the downloaded update + restart.
  ipcMain.handle("aios:install-update", async () => {
    if (!app.isPackaged) return { ok: false, reason: "not-packaged" };
    try {
      // isSilent: pass /S to NSIS to suppress the installer UI on update
      // installs (only honored when the installed shell supports it; with
      // assistedInstaller / oneClick:false the wizard may briefly flash, but
      // the flag is the strongest signal we can pass).
      // isForceRunAfter: relaunch the app automatically once install finishes
      // so the user lands back in AIOS without having to double-click again.
      autoUpdater.quitAndInstall(true, true);
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

let isCleaningUp = false;
app.on("before-quit", (event) => {
  if (isCleaningUp) return;
  isCleaningUp = true;
  event.preventDefault();
  scheduler?.stop();
  globalShortcut.unregisterAll();
  destroyControlBubble();
  destroyControlPopup();
  destroyCursorOverlay();
  // host.stop() may be async — fire it, then exit on settle. Give it a 1.5s
  // ceiling so a wedged Python sidecar can't keep the app from quitting.
  const stopHost = Promise.resolve(host?.stop()).catch(() => undefined);
  const watchdog = new Promise<void>((resolve) => setTimeout(resolve, 1500));
  Promise.race([stopHost, watchdog]).finally(() => app.exit(0));
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
